In [1]:
import os
import sys

In [4]:

from ripser import ripser

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [2]:

%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from skimage.filters import threshold_otsu
from scipy.ndimage.morphology import distance_transform_edt



In [3]:
import tcripser
import gudhi,gudhi.hera,gudhi.wasserstein,persim

In [4]:
import mdtraj

In [6]:
os.chdir("Z:/data/micelles/")

In [7]:
f=mdtraj.load("Micelles_for_seth.gro")

In [8]:
p0Gro=mdtraj.load("p0-only.gro")

In [10]:
f.__dict__.keys()

dict_keys(['_topology', '_xyz', '_rmsd_traces', '_unitcell_lengths', '_unitcell_angles', '_time_default_to_arange', '_time'])

In [19]:
atomIds=[a.index for a in f.topology.atoms if a.element.symbol!="H"]


In [21]:
atom = f.topology.atom(10)
print('''Hi! I am the %sth atom, and my name is %s.
I am a %s atom with %s bonds.
I am part of an %s residue.''' % ( atom.index, atom.name, atom.element.name, atom.n_bonds, atom.residue.name))

Hi! I am the 10th atom, and my name is EO.
I am a virtual_site atom with 0 bonds.
I am part of an PEPP residue.


In [23]:
print('All atoms: %s' % [atom for atom in f.topology.atoms])

All atoms: [PEPP1-SP2, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-PO40, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-EO, PEPP1-SP2, PEPP2-SP2, PEPP2-EO, PEPP2-EO, PEPP2-EO, PEPP2-EO, PEPP2-EO, PEPP2-EO, PEPP2-EO,

In [30]:
print('All atomNames: %s' % [atom.name for atom in f.topology.atoms])

All atomNames: ['SP2', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'SP2', 'SP2', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'EO', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO40', 'PO

In [25]:

print('All residues: %s' % [residue for residue in f.topology.residues])


All residues: [PEPP1, PEPP2, PEPP3, PEPP4, PEPP5, PEPP6, PEPP7, PEPP8, PEPP9, PEPP10, PEPP11, PEPP12, PEPP13, PEPP14, PEPP15, PEPP16, PEPP17, PEPP18, PEPP19, PEPP20, PEPP21, PEPP22, PEPP23, PEPP24, PEPP25, PEPP26, PEPP27, PEPP28, PEPP29, PEPP30, PEPP31, PEPP32, PEPP33, PEPP34, PEPP35, PEPP36, PEPP37, PEPP38, PEPP39, PEPP40, PEPP41, PEPP42, PEPP43, PEPP44, PEPP45, PEPP46, PEPP47, PEPP48, PEPP49, PEPP50, PEPP51, PEPP52, PEPP53, PEPP54, PEPP55, PEPP56, PEPP57, PEPP58, PEPP59, PEPP60]


### SEP ALL PO

In [18]:
numFrames,numAtoms,_=f.xyz.shape# numFrames,numAtoms, (x,y,z)

(51, 4920, 3)

In [11]:
f.__dict__['_time'] #picosecs? -> 10ns between frame

array([1500000., 1510000., 1520000., 1530000., 1540000., 1550000.,
       1560000., 1570000., 1580000., 1590000., 1600000., 1610000.,
       1620000., 1630000., 1640000., 1650000., 1660000., 1670000.,
       1680000., 1690000., 1700000., 1710000., 1720000., 1730000.,
       1740000., 1750000., 1760000., 1770000., 1780000., 1790000.,
       1800000., 1810000., 1820000., 1830000., 1840000., 1850000.,
       1860000., 1870000., 1880000., 1890000., 1900000., 1910000.,
       1920000., 1930000., 1940000., 1950000., 1960000., 1970000.,
       1980000., 1990000., 2000000.])

In [33]:
p0Index=[a.index for a in f.topology.atoms if a.name.find('PO')!=-1]


19

In [35]:
p0Gro=f #probably modifies f, but no .copy()?
p0Gro.restrict_atoms(p0Index)
p0Gro.save("p0-only.gro")


In [36]:
p0Gro

<mdtraj.Trajectory with 51 frames, 2580 atoms, 60 residues, and unitcells at 0x1ff60e01640>

In [44]:
!pip uninstall ripser

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [9]:
cords=p0Gro.xyz[0,:]
cords

array([[21.111, 12.05 , 18.995],
       [21.107, 11.801, 18.754],
       [21.349, 11.843, 18.498],
       ...,
       [15.267,  9.261, 15.036],
       [15.583,  9.455, 15.023],
       [15.659,  9.741, 14.989]], dtype=float32)

In [48]:
cords[0]-cords[1]

array([0.00399971, 0.24900055, 0.24100113], dtype=float32)

In [52]:
from scipy.spatial import distance_matrix

In [55]:
dMat=distance_matrix(cords,cords)
dMat

array([[0.        , 0.34655276, 0.58864587, ..., 7.58976573, 7.28488858,
        7.1486937 ],
       [0.34655276, 0.        , 0.35477403, ..., 7.37432855, 7.0667286 ,
        6.93538187],
       [0.58864587, 0.35477403, 0.        , ..., 7.45941669, 7.1431738 ,
        7.00768037],
       ...,
       [7.58976573, 7.37432855, 7.45941669, ..., 0.        , 0.37102708,
        0.62150915],
       [7.28488858, 7.0667286 , 7.1431738 , ..., 0.37102708, 0.        ,
        0.29787269],
       [7.1486937 , 6.93538187, 7.00768037, ..., 0.62150915, 0.29787269,
        0.        ]])

In [56]:
rip=ripser.ripser(dMat,maxdim=3,distance_matrix=True)


NameError: name 'ripser' is not defined

In [58]:
!pip install ripser


ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [10]:
for frame in range(len(p0Gro.xyz)):
    np.save(f"toMac/Ptraj{frame}.npy",p0Gro.xyz[frame,:])

